### ISSUE TITLE
Manila.js 016 (February 2016)

### ISSUE THREAD

**Issue by richardneililagan** [manilajs/manilajs.com#14]
Subscribe to this thread for updates. Feel free to send a PR to update the site when enough info is available.
#### Event
- [x] Date - `February 5, Friday`
- [x] Hero image - `https://unsplash.com/photos/NuE8Nu3otjo`
#### Venue
- [x] Name `VentureSpace`
- [x] Icon

> Set this to the logo shown on their Facebook page --- should update if they have a different logo.
- [x] URL `https://www.facebook.com/VentureSpacePH/`

> Can't find a standalone landing for VentureSpace PH --- should update this link if they actually have a standalong site.
- [x] Address `724 Shaw Boulevard`
- [x] Google maps URL `https://goo.gl/maps/wbPWmDD9vn72`

> _Note on the Google maps streetview_ : looks like their building was still under construction when the streetview images were taken --- this link's map matches the one they have on their Facebook page though, so yeah.
#### Venue details

(usually detailed in blog post and welcome emails)
- [x] How many attendees can you accommodate? `70-100`
- [x] Do attendees need ID's?  `assume yes`
- [x] Is there a dress code for the building? `no`
- [x] Projector? `yes!`
- [x] Wifi? `yes (for speakers at least)`
- [x] Space for food? `yes`
- [x] Parking space available for attendees? `YES`
- [x] Will you like to sponsor food? `yes!`
#### Speaker 1
- [x] Name `Joe Palala`
- [x] URL http://jpalala.com
- [x] Avatar http://i.imgur.com/eVxJXQN.jpg
- [x] Company/title `Cognizant`
- [x] GitHub username `jpalala`
- [x] Twitter username `jpalala`
- [x] Description of talk
  
  > **Asyncs, promises, and avoiding callback hell**<br>
  > Let's learn with how to deal with complexities in wrangling long-running functions, and how to harness JavaScript's power to build fast, reliable apps while dealing with asynchronous callbacks.
#### Speaker 2
- [x] Name `Rico Sta. Cruz`
- [x] URL `http://ricostacruz.com`
- [x] Avatar `http://i.imgur.com/r36mMyr.jpg`
- [x] Company/title `Mashup Garage`
- [x] GitHub username `rstacruz`
- [x] Twitter username `rstacruz`
- [x] Description of talk
  
  > Are you wondering why npm is slow? Rico will be sharing his experiences in building pnpm, a faster implementation of npm.
#### External stuff
- [x] Google forms signup sheet
- [x] Welcome reminders blog post

**Comment by marksteve** [comment]
QC or Ortigas plox :))

**Comment by richardneililagan** [comment]
Hahaha, yes please! :D Although, parang I remember @rstacruz saying na Ortigas na talaga 016.

**Comment by marksteve** [comment]
We're using Jerry Tieng's place this Jan 30 for the Python meetup. Maybe we can use that too? It's in Ortigas.

**Comment by rstacruz** [comment]
Thanks for taking initiative on this! Yes, we're using Jerry's place too. Been talking to him to finalize details. :-)

> Venue: **VentureSpace**
> Address: 724 Shaw Boulevard

**Comment by rstacruz** [comment]
Speaker 1:

> Joe Palala
> Asynchronous JavaScript with async and promises

**Comment by rstacruz** [comment]
w00t, let's get these announcements in time for next week

**Comment by richardneililagan** [comment]
Yosh! Sige, will reach out to Joe as well for his personal details to display on site. Will update the PR with the changes.

Are we go for a talk from you as well @rstacruz ? Or is that not final yet?

**Comment by rstacruz** [comment]
what topic do you suggest?

**Comment by richardneililagan** [comment]
I recall that you had a topic in mind when you suggested actually --- but if I was to suggest, why not tape? You've been doing a bunch of stuff on it lately, it's been recently gaining good traction, and I _always_ get people asking me about how testing works on JS anyway. Might make for a good segue / springboard.

**Comment by rstacruz** [comment]
filled in more details

**Comment by rstacruz** [comment]
> Can't find a standalone landing for VentureSpace PH --- should update this link if they actually have a standalong site. —@richardneililagan

Jerry said they don't have one yet :o That's fine though

**Comment by rstacruz** [comment]
Blog post is up! manilajs.com/p/016-welcome

**Comment by rstacruz** [comment]
Blog post is up! http://manilajs.com/p/016-welcome
