### ISSUE TITLE
Manila.js 014 (August 2015)

### ISSUE THREAD

**Issue by rstacruz** [manilajs/manilajs.com#6]
Subscribe to this thread for updates. Feel free to send a PR to update the site when enough info is available.
#### Event
- [x] Date `August 7, Friday`
- [x] Hero image
#### Venue
- [x] Name `Mayon Studios, Inc.`
- [x] Icon
- [x] URL https://www.facebook.com/MayonStudios
- [x] Address `19th Flr, Jecoprime Bldg. 20th Drive, McKinley Parkway, BGC, Taguig`
- [x] Google maps URL https://goo.gl/maps/rLFOn
#### Venue details

(usually detailed in blog post and welcome emails)
- [x] How many attendees can you accommodate? `enough`
- [x] Do attendees need ID's? `false`
- [x] Is there a dress code for the building? `false`
- [x] Projector? `true`
- [x] Wifi? `false`
- [x] Space for food? `true`
- [x] Parking space available for attendees? `with fee`
- [x] Will you like to sponsor food? `true`
#### Speaker 1
- [x] Name `Arjay Elbore`
- [x] URL
- [x] Avatar
- [x] Company/title
- [x] GitHub username
- [x] Twitter username
- [x] Description of talk
#### Speaker 2
- [ ] Name
- [ ] URL
- [ ] Avatar
- [ ] Company/title
- [ ] GitHub username
- [ ] Twitter username
- [ ] Description of talk
#### External stuff
- [ ] Google forms signup sheet
- [ ] Welcome reminders blog post

**Comment by rstacruz** [comment]
Update: Mayon Studios will host the August meetup instead of July.

**Comment by rstacruz** [comment]
Speakers:

- Rajay Rajay on Typescript
- Neil Gardoce of Aelogica `...`

**Comment by rstacruz** [comment]
Update: here's our speakers for August.
- Rajay Rajay of `...` on Typescript
- ~~Neil Gardose of Aelogica on `...`~~

**Comment by richardneililagan** [comment]
These issues should probably be milestones, I think. So we can create individual issue items, have those assigned / owned by anyone interested, and track accordingly.

If I wanted to take on doing the updates for speakers, it'd probably be best if there was an indication that I'm already working on it, yeah? <3

Probably for something moving forward though.

**Comment by rstacruz** [comment]
pwede, but there's really just 2 things here: (1) venue, (2) speakers, should we separate them into 2 issues? haha

**Comment by rstacruz** [comment]
it's actually pretty useful to collate all that info into one issue — say, marksteve was able to make PR #10 out of it

**Comment by rstacruz** [comment]
Site is up! Speaker 1 is Arjay Elbore on Typescript. Speaker 2 is someone from PlayNGo—still waiting on his talk details.
